const SERVER_HOST = "192.168.31.222";

const SERVER_PORT = 8777;

window.CONSTS = {
    SERVER_HOST: SERVER_HOST,
    SERVER_PORT: SERVER_PORT,
    SERVER_URL: `http://${SERVER_HOST}:${SERVER_PORT}`,
    WS_SERVER_URL: `ws://${SERVER_HOST}:${SERVER_PORT}`,
};
