services:
  redis_cache:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    restart: on-failure
    env_file: .env

  msg_db:
    image: postgres:17.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
       - 5632:${DB_PORT}
    restart: on-failure
    env_file: .env
    volumes:
      - ./pinger_db:/var/lib/postgresql/data

  api_server:
    build:
      context: .
      dockerfile: api_server/Dockerfile
    ports:
      - "8777:8777"
    depends_on:
      - redis_cache
      - msg_db
      - bot_notificator
    restart: on-failure
    env_file: .env

  bot_notificator:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: on-failure
    env_file: .env

  messanger_client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - api_server
    ports:
      - "5173:5173"
    restart: on-failure

volumes:
  msg_db: