"""changed message content from Text to String(500)

Revision ID: 2553102359a0
Revises: 307b2391372d
Create Date: 2024-10-21 22:39:21.525746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2553102359a0'
down_revision: Union[str, None] = '307b2391372d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
